name: Sonar (consume reusable)

on:
  push:
    branches: [main]

jobs:
  sonar:
    uses: sonar-local/workflows/.github/workflows/sonar-reusable.yml@d2d086100879e4c0866cd9798d60d66c294fdeae
    with:
      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
